GET http://localhost:3003/endereco/05424150
###

POST http://localhost:3003/create-team
Content-Type: application/json

{
    "name": "teste"
}

###
post https://cep-labenu.herokuapp.com/user/05424150

###
POST http://localhost:3003/create-student
Content-Type: application/json

{
    "name":"Olovaldo Nogueira",
    "email":"olovaldo_teste@gmail.com",
    "data_nasc": "1995-12-02",
    "turma_id": "f2b987b9-8ca4-47dd-8d8b-d1c104527079"
}


###
GET http://localhost:3003/list


###
GET http://localhost:3003/student/testezinho

